### ISSUE TITLE
rdflib missing from dependencies

### ISSUE THREAD

**Issue by BonaBeavis** [oeg-upm/Chowlk#11]
I use the converter script standalone for a workflow and have to install rdflib explicitly to get it working.

**Comment by Serge3006** [comment]
Hi, how do you plan to integrate it into your workflow? A feature that I still have to document is the possibility to use Chowlk as a web service. You would have to access the following endpoint:

curl -F 'data=@/path/to/diagram/diagram.xml' https://chowlk.linkeddata.es/api

You can send the diagram in XML and the service will return the ontology in TTL.

Let me know if that works for you.

**Comment by BonaBeavis** [comment]
I try to automate the ontology engineering [workflow](https://gitlab.com/kupferdigital/ontology/-/blob/master/images/chowlk/Dockerfile)
I use the chowlk diagrams as an input mode for the domain experts, convert them to turtle for the ontology and export a picture for the documentation.
What I need is just a cli converter where the input is a chowlk diagramm and the output is some rdf serialization.
Right now I hacked it together, see [here](https://gitlab.com/kupferdigital/ontology/-/blob/master/images/chowlk/Dockerfile).

Maybe you could create a pip package, which which wraps `converter.py` for shell usage?

**Comment by Serge3006** [comment]
Hi, for now I've updated the requirements.txt so no dependencies will be missing. On the other hand you could call the converter with the following line:
```
python converter.py path/to/diagram.xml output/path/ontology.ttl
```
I will create a pip package so you can call the internal functions programmatically, but for now, I think that could be a solution.

**Comment by BonaBeavis** [comment]
thx!
