### ISSUE TITLE
Tuple size mismatch

### ISSUE THREAD

**Issue by BonaBeavis** [oeg-upm/Chowlk#19]
This line throws a tuple size mismatch:

https://github.com/oeg-upm/Chowlk/blob/d8fd6b5cb475185889516743c4c4d3b14cb171cc/converter.py#L11

**Comment by Serge3006** [comment]
Hi, I've tested this with some data and I've not faced this problem. Is it still giving you errors?

**Comment by BonaBeavis** [comment]
My static code checker is also complaining:

The function returns 6 values:

https://github.com/oeg-upm/Chowlk/blob/d8fd6b5cb475185889516743c4c4d3b14cb171cc/source/chowlk/transformations.py#L53

But in converter.py it gets unpacked to 4.

**Comment by Serge3006** [comment]
Hi, you were right, the code was not updated, sorry for that, now it should be solved.

**Comment by BonaBeavis** [comment]
Works fine now, thanks a lot!
