### ISSUE TITLE
owl:imports does not work

### ISSUE THREAD

**Issue by mariapoveda** [oeg-upm/Chowlk#28]
The object of owl:import should be URIs, not text. Example attached.

[adapters.xml.zip](https://github.com/oeg-upm/Chowlk/files/8169253/adapters.xml.zip)

**Comment by Serge3006** [comment]
Not sure if this is an issue, when the value of the owl:imports property is changed to a URI without quotation marks neither turtle validators nor Protege recognize the file. They output an error while loading the file.

![image](https://user-images.githubusercontent.com/30761241/156891215-a0372ea7-7070-4dc2-80d9-1b156f3faa3d.png)

**Comment by mariapoveda** [comment]
It should have <> as it is an uri.
