### ISSUE TITLE
Why are restriction defined with subClass instead of equivalentClass

### ISSUE THREAD

**Issue by GordianDziwis** [oeg-upm/Chowlk#33]
For example the existential estriction is in the chowlk notation defined with rdfs:subClass:
```turtle
ns:Parent rdf:type owl:Class ;
  rdfs:subClassOf [ 
   rdf:type owl:Restriction ;
   owl:onProperty :hasChild;
   owl:someValuesFrom :Person
 ] .
```
So when x is a Parent follows => x has a child y which is a person.
But the other direction is not implied, because Parent is only a subClass of the anonymous concept of having a child which is a person.

While in the owl-primer existential estrictions are defined with 
```turtle
 :Parent  owl:equivalentClass  [
   rdf:type            owl:Restriction ;
   owl:onProperty      :hasChild ;
   owl:someValuesFrom  :Person
 ] .
```

Which would go both ways. So my questions are:
1. What is the reasoning for using subClass insteadof equivalentClass.
2. How to express the equivalentClass case with chowlk?

**Comment by GordianDziwis** [comment]
Also why does chowlk explicitly state that: ns:Parent rdf:type owl:Class, when this already implied by the rdfs:subClass property's domain.

**Comment by mariapoveda** [comment]
Hello Bona, 


1.     What is the reasoning for using subClass insteadof equivalentClass. --> both are possible by stating subClass or equivalntClass. The shortcut had to take only one of the options and from our experirence subclassOf was used more times, also it has less implications in case of error.

3.     How to express the equivalentClass case with chowlk? --> use the equivalent to an anonymous class then the axiom.

**Comment by GordianDziwis** [comment]
Thanks!
