### ISSUE TITLE
Add `owl:hasValue` to notation

### ISSUE THREAD

**Issue by GordianDziwis** [oeg-upm/Chowlk#34]
![image](https://user-images.githubusercontent.com/3330855/169703773-2d2920cb-4577-44f6-9a73-d08a33dd1e17.png)

```turtle
 :JohnsChildren  owl:equivalentClass  [
   rdf:type        owl:Restriction ;
   owl:onProperty  :hasParent ;
   owl:hasValue    :John
 ] .
```

**Comment by mariapoveda** [comment]
Thanks, it makes sense. Maybe hasValue to be closer to the owl construct.

Would you use the same notation (rectangle) for data values?

**Comment by GordianDziwis** [comment]
I thought the notation for data values is a rectangle with the content `"value"^^datatype`?

**Comment by Sergio-Carulli** [comment]
Value constraints have been implemented. Please see https://chowlk.linkeddata.es/notation.html#restriction-value-constraint-identifier
