### ISSUE TITLE
Add `owl:oneOf` to notation

### ISSUE THREAD

**Issue by GordianDziwis** [oeg-upm/Chowlk#35]
![image](https://user-images.githubusercontent.com/3330855/169704301-a9f2a657-f58b-488c-a141-5ea8a537251f.png)

```turtle
 :MyBirthdayGuests  owl:equivalentClass  [
   rdf:type   owl:Class ;
   owl:oneOf  ( :John  :Mary )
 ] .
```

**Comment by mariapoveda** [comment]
Thank you Bona ,

 wer are considering this option too https://chowlk.linkeddata.es/notation.html#all-different 

What do you think?

**Comment by GordianDziwis** [comment]
Not sure what you mean with this option? Because allDifferent is not the same as oneOf, or do you refer to the notation?

**Comment by Sergio-Carulli** [comment]
Enumeration of individuals and data values have been added to Chowlk. Please see https://chowlk.linkeddata.es/notation.html#enumeration-identifier
