### ISSUE TITLE
Add qualified cardinality restrictions

### ISSUE THREAD

**Issue by GordianDziwis** [oeg-upm/Chowlk#45]
Just demanding stuff ;)

**Comment by Sergio-Carulli** [comment]
Qualified Cardinalities have been implemented and added to the library which you can download from the Chowlk main page or https://chowlk.linkeddata.es/static/resources/chowlk-library-complete.xml

To see how to use them please see https://chowlk.linkeddata.es/notation.html#restriction-qualified-cardinality-constraint-identifier
