### ISSUE TITLE
Allow IRIs in annotation block

### ISSUE THREAD

**Issue by GordianDziwis** [oeg-upm/Chowlk#46]
For example
```
dc:creator: Full Name
owl:versionInfo: 0.0.1
dc:title: Template Ontology
owl:imports: <https://kupferdigital.gitlab.io/ontologies/materials#>
```

Right know the object of 'owl:imports' will be converted to a string:
```ttl
cd: a owl:Ontology ;
    dc:creator "Full Name" ;
    dc:description "Ontology code created by Chowlk" ;
    dc:title "Template Ontology" ;
    owl:imports "<https://kupferdigital.gitlab.io/ontologies/materials#>" ;
    owl:versionInfo "0.0.1" .
```

**Comment by mariapoveda** [comment]
@Sergio-Carulli Could you have a look at this issues? Another example: 

` cc:license: <https://creativecommons.org/licenses/by/4.0/>`

**Comment by Sergio-Carulli** [comment]
Now IRIs are allowed in annotation block. To see how to create an Annotation Block please see https://chowlk.linkeddata.es/notation.html#ontology_metadata
