### ISSUE TITLE
Suppoort owl:AnnotationProperty

### ISSUE THREAD

**Issue by mariapoveda** [oeg-upm/Chowlk#55]
Add owl:AnnotationProperty definitions using the diamond symbols as for object properties and datatype properties.

**Comment by Sergio-Carulli** [comment]
The Annotation Properties are described at https://chowlk.linkeddata.es/notation.html#annotation-properties

The Annotation Properties has been added to the library and can be downloaded from the Chowlk homepage or from https://chowlk.linkeddata.es/static/resources/chowlk-library-complete.xml
