### ISSUE TITLE
add owl:inverseOf  to the template

### ISSUE THREAD

**Issue by mariapoveda** [oeg-upm/Chowlk#60]
Add both options to represent owl:inverseOf

**Comment by Sergio-Carulli** [comment]
The "owl:inverseOf" property relationship is described at https://chowlk.linkeddata.es/notation.html#inverse-property-object-property

The property relationship "owl:inverseOf" has been added to the library and can be downloaded from the Chowlk homepage or from https://chowlk.linkeddata.es/static/resources/chowlk-library-complete.xml
