### ISSUE TITLE
add Minimum metadata fields according to FAIR IMPACT

### ISSUE THREAD

**Issue by mariapoveda** [oeg-upm/Chowlk#61]
Add a block with minimum metadata fields according with FAIR-IMPACT project

**Comment by mariapoveda** [comment]
Done.

**Comment by Sergio-Carulli** [comment]
The metadata block is described at https://chowlk.linkeddata.es/notation.html#ontology_metadata

The metadata block has been added to the library and can be downloaded from the Chowlk homepage or from https://chowlk.linkeddata.es/static/resources/chowlk-library-complete.xml
