### ISSUE TITLE
Issue when importing the library into an "old" diagram

### ISSUE THREAD

**Issue by aljoshakoecher** [oeg-upm/Chowlk#63]
Hey, thank you for your efforts in creating chowlk - I really like the idea behind it 👍 
I just wanted to try it out and imported the chowlk library into diagrams.net like you describe on https://chowlk.linkeddata.es/.
Ttried it on an "old" diagram, i.e., a diagram with elements in it and got the following error in a popup dialog:
![image](https://github.com/oeg-upm/Chowlk/assets/50097079/9ba5f915-71b8-4b50-8b53-e04db2fc62b3)
Looking into the console logs, it seems to be a problem with a wrong / unexpected character?
```
INFO InvalidCharacterError undefined undefined undefined DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
```

I then simply created a new diagram and was able to import the library without any problems. So I think it's just a minor issue, but I just wanted to let you know since I stumbled upon it.

**Comment by Sergio-Carulli** [comment]
Hello,

Thank you for your support!! Can you send us the file in question and the library to chowlk@delicias.dia.fi.upm.es? We will try to replicate the error in order to fix it.

**Comment by aljoshakoecher** [comment]
Unfortunately, I didn't save the diagram. It had only one class in it and when I saw that it causes a problem, I just tested it with a fresh diagram. It was afterwards that I thought about reporting this as an issue here...

I now tried to reproduce the problem, but I can't - so I think this can be closed for now? Sorry for not being able to provide more infos.

**Comment by Sergio-Carulli** [comment]
Thank you for your help and time! Any other problems you encounter do not hesitate to contact us.
