### ISSUE TITLE
Add error reports

### ISSUE THREAD

**Issue by paoespinozarias** [oeg-upm/Chowlk#64]
For those of us who are running this tool from source code (without using the web application option) it would be very useful to get the _"xml_error_generated_" and "_xml_error_file_" that are available in the web service. This way if there are any errors in the diagram they can be checked more easily.

**Comment by Sergio-Carulli** [comment]
A new optional parameter has been added to generate the xml with the errors. For how to generate it please see https://github.com/oeg-upm/Chowlk?tab=readme-ov-file#to-convert-a-diagram
