### ISSUE TITLE
Min and Max cardinality

### ISSUE THREAD

**Issue by Serge3006** [oeg-upm/Chowlk#7]
In OWL minQualifiedCardinality and maxQualifiedCardinality do not exist, those are from OWL 2, change them to min and maxCardinality.

**Comment by Serge3006** [comment]
Done bd73cf596a23eb8e9688717525e6852a1fdbf304

**Comment by GordianDziwis** [comment]
Why do you target owl and not owl2?

**Comment by mariapoveda** [comment]
We are adding OWL2 consruct on demand gradually.
